---
- name: Configure Firewall
  hosts: all
  become: yes
  tasks:
    - name: Install UFW on Ubuntu
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Firewalld on CentOS
      ansible.builtin.yum:
        name: firewalld
        state: present
      when: ansible_distribution == "CentOS"

    - name: Enable UFW on Ubuntu
      ansible.builtin.command: ufw enable
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable Firewalld on CentOS
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Configure Firewall Rules for UFW
      ansible.builtin.command: ufw allow ssh
      when: ansible_distribution == "Ubuntu"

    - name: Configure Firewall Rules for Firewalld
      ansible.builtin.firewalld:
        port: 22/tcp
        permanent: yes
        state: enabled
      when: ansible_distribution == "CentOS"
